## numpy:
### numpy is python library stand for numerical python and use to perform numerical opeartion 
### it uses numpy ndarray over python list as they are faster

## properties of numpy ndarray are 

###  1) mulable
###  2) Homogeneous data 
###  3) n dimentions
###  4) Duplicate allowed
###  5) sequencial/


## Why numpy is faster
### 1) numpy is mostly written is c/c++
### 2)also numpy store data in contineous memory block 
### 3) it has featurs like vectorization and broadcasting

In [6]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [4]:
import numpy as np

In [8]:
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [9]:
l =[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]
print(l)
print(type(l))

[[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]]
<class 'list'>


In [11]:
a=np.array(l)
print(a)
print(type(a))

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
<class 'numpy.ndarray'>


In [15]:
a=np.zeros(3)
print(a)
print(type(a))

print("_"*30)

a = np.zeros((2,4,3))#np.zeros((metrix,row of matrix,column of metrix))
print(a)
print(type(a))

[0. 0. 0.]
<class 'numpy.ndarray'>
______________________________
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
<class 'numpy.ndarray'>


In [20]:
a=np.ones(3)
print(a)
print("_"*40)

a=np.ones((3,4))#np.ones((metrix,row of matrix,column of metrix))
print(a)
print(type(a))

[1. 1. 1.]
________________________________________
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [30]:
a=np.eye(4,6)#np.eye(metrix,row of matri)         # digonal value are 1 other is (0)zero
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [33]:
a=np.full((3),10)
print(a)

print("_"*40)

a= np.full((3,4,5),6)##np.full((metrix,row of matri,column of metrix),value)
print(a)

[10 10 10]
________________________________________
[[[6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]]

 [[6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]]

 [[6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]]]


In [39]:
a=np.random.rand(2,4)#no.random.rand(no. of rows , no of column)
print(a)

[[0.38784784 0.68538325 0.91233394 0.59911628]
 [0.49191404 0.9512205  0.70224121 0.79759286]]


In [40]:
a = np.array([[32800,2,3],[1,2,3]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[[32800     2     3]
 [    1     2     3]]
2
(2, 3)
6
int32


In [44]:
a=np.array([1,2,3])
x=a.copy()
x[0]=10
print("original : ",a)
print("copy : ",x)

print("*"*40)

a=np.array([1,2,3])
x=a.view()
b=a
c=x

x[0]=10
print("original : ",a)
print("copy : ",x)

print("*"*40)

print("copy b : ",b)
print("copy c : ",c)

original :  [1 2 3]
copy :  [10  2  3]
****************************************
original :  [10  2  3]
copy :  [10  2  3]
****************************************
copy b :  [10  2  3]
copy c :  [10  2  3]


In [3]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("orignal : ")
print(a)
print("dim",a.ndim)

orignal : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
dim 2


In [6]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("orignal : ")
print(a)
print("dim",a.ndim)

orignal : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
dim 2


In [7]:
print(a)
print()
print(a[0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[1 2 3 4]


In [56]:
print(a)
print(a[0:1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]]


In [58]:
print(a)
print()
print(a[2,1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

10


In [59]:
print(a)
print()
print(a[:2,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[1 2 3 4]
 [5 6 7 8]]


In [60]:
print(a)
print()
print(a[:,1:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [61]:
print(a)
print()
print(a[1,1:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[6 7 8]


In [62]:
print(a)
print()
print(a[1:3,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 6  7]
 [10 11]]


In [63]:
print(a)
print()
print(a[2,1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

10


In [67]:
print(a)
print()
print(a[-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[ 9 10 11 12]


In [72]:
a=np.array([[[1,2,3],[11,22,33]],
           [[4,5,6],[44,55,66]]])

print(a)
print("*"*45)
print(a[0,:,1:])
print(a.ndim)

[[[ 1  2  3]
  [11 22 33]]

 [[ 4  5  6]
  [44 55 66]]]
*********************************************
[[ 2  3]
 [22 33]]
3


# array operations:

## Append:

In [85]:
a=np.array([1,2,3])
print("oringnal : ",a)
print("dimention",a.ndim)
print("*"*45)
b=np.append(a,[4,5,6])
print("aftre append : ",b)
print("dimention",b.ndim)

oringnal :  [1 2 3]
dimention 1
*********************************************
aftre append :  [1 2 3 4 5 6]
dimention 1


In [91]:
a=np.array([[1,2,3],[1,2,3],[1,2,3]])
print("oringnal : ",a)
print("dimention",a.ndim)
print("*"*45)
b=np.append(a,[[4,5,6]])
print("aftre append : ",b)
print("dimention",b.ndim)


oringnal :  [[1 2 3]
 [1 2 3]
 [1 2 3]]
dimention 2
*********************************************
aftre append :  [1 2 3 1 2 3 1 2 3 4 5 6]
dimention 1


In [102]:
c=np.append(a,[[4,44],[5,55],[6,66]],axis=1)
print(c)
print(c.ndim)
print(c.shape)
print(c.size)

[[ 1  2  3  4 44]
 [ 1  2  3  5 55]
 [ 1  2  3  6 66]]
2
(3, 5)
15


In [103]:
c=np.append(a,[[1,2,3],[1,2,3]],axis=0)
print(c)
print(c.ndim)
print(c.shape)
print(c.size)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
2
(5, 3)
15


In [14]:
import numpy as np
print("3 dimentional array")
a=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print("original   : \n",a)
print("dim",a.ndim)
print("_"*45)

c=np.append(a,[[[1],[1]],[[1],[1]]],axis=2)
print("after horizontal insert with single alements \n",c)
print("dim",c.ndim)
print("_"*45)

b=np.array([[[1],[1]],[[1],[1]]])
print(b)
print("_"*30)
print("shape of b",b.shape)
print("dim",a.ndim)

3 dimentional array
original   : 
 [[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
dim 3
_____________________________________________
after horizontal insert with single alements 
 [[[1 2 3 1]
  [1 2 3 1]]

 [[1 2 3 1]
  [1 2 3 1]]]
dim 3
_____________________________________________
[[[1]
  [1]]

 [[1]
  [1]]]
______________________________
shape of b (2, 2, 1)
dim 3


In [27]:
import numpy as np
print("3 dimentional array")
a=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print("original   : \n",a)
print("dim",a.ndim)
print("_"*45)

c=np.append(a,[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]],axis=1)
print("after horizontal insert with single alements \n",c)
print("dim",c.ndim)
print("_"*45)

b=np.array([[[1],[1]],[[1],[1]]])
print(b)
print("_"*30)
print("shape of b",b.shape)
print("dim",a.ndim)

3 dimentional array
original   : 
 [[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
dim 3
_____________________________________________
after horizontal insert with single alements 
 [[[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]]
dim 3
_____________________________________________
[[[1]
  [1]]

 [[1]
  [1]]]
______________________________
shape of b (2, 2, 1)
dim 3


In [28]:
import numpy as np
print("3 dimentional array")
a=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print("original   : \n",a)
print("dim",a.ndim)
print("_"*45)

c=np.append(a,[[[1,2,3],[1,2,3]]],axis=0)
print("after horizontal insert with single alements \n",c)
print("dim",c.ndim)
print("_"*45)

b=np.array([[[1],[1]],[[1],[1]]])
print(b)
print("_"*30)
print("shape of b",b.shape)
print("dim",a.ndim)

3 dimentional array
original   : 
 [[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
dim 3
_____________________________________________
after horizontal insert with single alements 
 [[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
dim 3
_____________________________________________
[[[1]
  [1]]

 [[1]
  [1]]]
______________________________
shape of b (2, 2, 1)
dim 3


In [29]:
a=np.array([1,2,3])  
print("priginal  \n",a)
print("dim",a.ndim)
print("_"*45)

b= np.insert(a,2,4)
print("after insert : \n",b)
print("dim",b.ndim)

priginal  
 [1 2 3]
dim 1
_____________________________________________
after insert : 
 [1 2 4 3]
dim 1


In [33]:
print("2 dimnetional array")
a=np.array([[1,2,3,1],[1,2,3,1],[1,2,3,1]])
print("priginal  \n",a)
print("dim",a.ndim)
print("_"*45)

b= np.insert(a,0,4,axis=1)
print("after insert : \n",b)
print("dim",b.ndim)

2 dimnetional array
priginal  
 [[1 2 3 1]
 [1 2 3 1]
 [1 2 3 1]]
dim 2
_____________________________________________
after insert : 
 [[4 1 2 3 1]
 [4 1 2 3 1]
 [4 1 2 3 1]]
dim 2


In [41]:
print("2 dimnetional array")
a=np.array([[1,2,3,1],[1,2,3,1],[1,2,3,1]])
print("priginal  \n",a)
print("dim",a.ndim)
print("_"*45)

b= np.insert(a,0,[[1,2,3,5]],axis=0)
print("after insert :(0) axis=0 \n",b)
print("dim",b.ndim)
print("_"*45)

b= np.insert(a,-1,[[1,2,3,5]],axis=0)
print("after insert -1 axis=0 \n",b)
print("dim",b.ndim)

2 dimnetional array
priginal  
 [[1 2 3 1]
 [1 2 3 1]
 [1 2 3 1]]
dim 2
_____________________________________________
after insert :(0) axis=0 
 [[1 2 3 5]
 [1 2 3 1]
 [1 2 3 1]
 [1 2 3 1]]
dim 2
_____________________________________________
after insert -1 axis=0 
 [[1 2 3 1]
 [1 2 3 1]
 [1 2 3 5]
 [1 2 3 1]]
dim 2


In [45]:
print("2 dimnetional array")
a=np.array([[1,2,3,1],[1,2,3,1],[1,2,3,1]])
print("priginal  \n",a)
print("dim",a.ndim)
print("_"*45)

c=np.insert(a,2,[4,5,6],axis=1)
print("after horize insert all element  \n ",c,"\n dim",c.ndim)

2 dimnetional array
priginal  
 [[1 2 3 1]
 [1 2 3 1]
 [1 2 3 1]]
dim 2
_____________________________________________
after horize insert all element  
  [[1 2 4 3 1]
 [1 2 5 3 1]
 [1 2 6 3 1]] 
 dim 2


In [53]:
a=np.array([[1,2,3],[11,12,13],[21,22,23]])
print("orignal : \n",a)
print("_"*45)

# c=np.delete(a,3)#it delete according to line by line reading
# print(c)
# print("_"*45)

# c=np.delete(a,[1,4,7])#it delete according to line by line reading
# print(c)
# print("_"*45)

orignal : 
 [[ 1  2  3]
 [11 12 13]
 [21 22 23]]
_____________________________________________


In [54]:
a=np.array([[1,2,3],[11,12,13],[21,22,23]])
print("orignal : \n",a)
print("_"*45)

c=np.delete(a,0,0)#it delete according to line by line reading
print(c)
print("_"*45)

c=np.delete(a,0,1)#it delete according to line by line reading
print(c)
print("_"*45)

orignal : 
 [[ 1  2  3]
 [11 12 13]
 [21 22 23]]
_____________________________________________
[[11 12 13]
 [21 22 23]]
_____________________________________________
[[ 2  3]
 [12 13]
 [22 23]]
_____________________________________________


In [57]:
a=np.array([[2,3]])

b=np.array([[4,3]])

print(np.concatenate((a,b)))
print("_"*45)

print(np.concatenate((b,a)))
print("_"*34)

[[2 3]
 [4 3]]
_____________________________________________
[[4 3]
 [2 3]]
__________________________________


In [59]:
print(b)
print("_"*45)
print(b.T)#transpose

[[4 3]]
_____________________________________________
[[4]
 [3]]


In [81]:
a=np.array([[1,2],[3,4]])

b=np.array([[5,6]])
print(a)
print("_"*45)

print(b)
print("_"*45)

# print(np.concatenate((a,b)),axis=0)
# print("_"*45)

# print(np.concatenate((a,b)),axis=1)
# print("_"*45)

# print(np.concatenate((a,b.T)),axis=1)
# print("_"*45)

# print(np.concatenate((a.T,b)),axis=1)
# print("_"*45)

[[1 2]
 [3 4]]
_____________________________________________
[[5 6]]
_____________________________________________


In [82]:
print(np.concatenate((a,b),axis=0))
print("_"*45)

[[1 2]
 [3 4]
 [5 6]]
_____________________________________________


In [83]:
print(np.concatenate((a,b.T),axis=1))
print("_"*45)

[[1 2 5]
 [3 4 6]]
_____________________________________________


In [89]:
print(np.concatenate((a.T,b),axis=0))

print("_"*45)

[[1 3]
 [2 4]
 [5 6]]
_____________________________________________


In [90]:
l=[1,2,3]
ll=[1,2,3]
print(l+ll)

[1, 2, 3, 1, 2, 3]


### .....................broadcasting in numpy......................................PENDDING
During calculations like add, multiply, difference etc. may need to consider the arrays of different shapes.

In NumPy such operations use broadcasting concepts when different shaped arrays are involved.

For same size arrays, binary operations can be performed on an element-by-element wise. #Broadcasting allows binary operations to be performed on arrays of different sizes as well.

This may occur in case of adding a scalar or 0-D array to another array of different size.

 This is possible by extending this smaller dimension array to arrays of higher dimension
 
 by stretching or duplicating the smaller dimension values to higher dimensions and adding to result.
 
Advantage of broadcasting is that this streching or duplication of values does not occur physically
rather it occurs as a logical model for purpose of calculation.


        Broadcasting in NumPy follows a strict set of rules for calculation in two arrays:
Rule 1: If the two arrays differ in their number of dimensions,
        the shape of the one with fever dimensions is padded with ones on its leading (left) side.
        
Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match           the other shape.

Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error known as value error is raised.
Calculation with same size arrays

     arrs np.array([1,2,3,4,51 arv2 np.array([2, 4, 5, 10, 20])

In [6]:
# Calculation with same size arrays
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,4,5,10,20])
res = arr1 * arr2
print("size arr1 :",arr1.size)
print("size arr2 :",arr2.size)
print(res)

size arr1 : 5
size arr2 : 5
[  2   8  15  40 100]


In [7]:
# Calculation with different size arrays
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,4,5,10,20])
res = arr1 * arr2
print("size arr1 :",arr1.size)
print("size arr2 :",arr2.size)
print(res)

size arr1 : 5
size arr2 : 5
[  2   8  15  40 100]


In [26]:
#Exaple 1:adding 2-D array to a 1-D array
arr1 = np.ones((2,3))
# print("arr1 ones : \n ",arr1)
# print("shape of arr1 : ",arr1.shape)
# print("-"*20)

arr2 = np.arange(3)#range in array form
# print("arr2 arange : \n",arr2)
# print("shape of arr2 : ",arr2.shape)

newarr = arr2.reshape(3,1) 
print(newarr)

newarr = arr1.reshape(3,2) 
print(newarr)

[[0]
 [1]
 [2]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [10]:
print(np.arange(1))
print(np.ones((2,3)))

[0]
[[1. 1. 1.]
 [1. 1. 1.]]


#                                benefit of using numpy

In [5]:
import time
t=time.time()
print(t)
a=np.array([i for i in range(5000)])
#multiplying 2
a2=[(i*2)+1 for i in a]
for i in a:
    a2.append((i*2)+1)
print(a2[:10])
print(time.time()-t)

1704787756.5935519
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
0.008673429489135742


In [6]:
import time
t=time.time()
print(t)
a3=np.array(a)
a3=(a3*2)+1
print(a3[:10])
print(time.time()-t)


1704787757.677854
[ 1  3  5  7  9 11 13 15 17 19]
0.0


In [7]:
a=np.arange(10,1,-2)
print(a)

[10  8  6  4  2]


# numpy function

In [9]:
a=np.arange(10)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


In [10]:
a=np.arange(2,10,3)
print(a)

[2 5 8]


In [11]:
a=np.arange(10)
print(a)
print(np.split(a,5))

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [12]:
a=np.arange(10)
print(a)
print(np.split(a,7))   #array split does not result in an equal division

[0 1 2 3 4 5 6 7 8 9]


ValueError: array split does not result in an equal division

In [13]:
a=np.arange(10)
print(np.split(a,[2,6]))
print(np.split(a,[3,4,7]))

[array([0, 1]), array([2, 3, 4, 5]), array([6, 7, 8, 9])]
[array([0, 1, 2]), array([3]), array([4, 5, 6]), array([7, 8, 9])]


In [14]:
a=np.arange(1,13)
print(a.shape)
print(a)
print("*"*20)
a1=a.reshape(3,2,2)
print(a1.shape)
print(a1)
print("*"*20)

a2=a.reshape(-1,3)
print(a2.shape)
print(a2)


(12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
********************
(3, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
********************
(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
a=np.arange(1,10)
print(a.dtype)
a[0]=9.56
print(a)

int32
[9 2 3 4 5 6 7 8 9]


In [16]:
a=a.astype(np.float16)
print(a.dtype)
a[0]=8.222
print(a)

float16
[8.22 2.   3.   4.   5.   6.   7.   8.   9.  ]


# ravel and flat

In [17]:
a=np.array([[[[[[[[[[1,2,3],[4,5,6]]]]]]]]]])
print(a)
print(a.ndim)


[[[[[[[[[[1 2 3]
         [4 5 6]]]]]]]]]]
10


In [18]:
print(np.ravel(a))#convert into the one d array 
print(a.ndim)

[1 2 3 4 5 6]
10


In [19]:
a=np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
print(a)
print("*"*15)
print(a[1])
print("*"*15)
print(a[1][1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]
***************
[[11 12 13]
 [14 15 16]]
***************
[14 15 16]


In [20]:
b=a.flat

In [21]:
print(b)

In [1]:
import numpy as np

# aggricate function

In [3]:
a=np.array([[1,5,4],[5,1,3],[2,6,3]])
print(a)
print("*"*23)
print(np.sort(a))#default row wise
print("*"*30)
print(np.sort(a,axis=1))#default row wise
print("*"*23)
print(np.sort(a,axis=0))#default column wise

[[1 5 4]
 [5 1 3]
 [2 6 3]]
***********************
[[1 4 5]
 [1 3 5]
 [2 3 6]]
******************************
[[1 4 5]
 [1 3 5]
 [2 3 6]]
***********************
[[1 1 3]
 [2 5 3]
 [5 6 4]]


In [5]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("_"*20)
print(a.sum())
print("_"*20)
print(np.sum(a,axis=1))#sum row wise
print("_"*20)
print(np.sum(a,axis=0))#columns
print("_"*20)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
____________________
45
____________________
[ 6 15 24]
____________________
[12 15 18]
____________________


In [6]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("_"*20)
print(a.min())
print("_"*20)
print(np.min(a,axis=1))#sum row wise
print("_"*20)
print(np.min(a,axis=0))#columns
print("_"*20)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
____________________
1
____________________
[1 4 7]
____________________
[1 2 3]
____________________


In [7]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("_"*20)
print(a.max())
print("_"*20)
print(np.max(a,axis=1))#sum row wise
print("_"*20)
print(np.max(a,axis=0))#columns
print("_"*20)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
____________________
9
____________________
[3 6 9]
____________________
[7 8 9]
____________________


In [8]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("_"*20)
print(a.mean())
print("_"*20)
print(np.mean(a,axis=1))#sum row wise
print("_"*20)
print(np.mean(a,axis=0))#columns
print("_"*20)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
____________________
5.0
____________________
[2. 5. 8.]
____________________
[4. 5. 6.]
____________________


## where function

In [14]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("_"*20)
print(np.where(a%2==0,222,a))#
print("_"*20)
print(np.where(a%2==0,a,111))#columns
print("_"*20)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
____________________
[[  1 222   3]
 [222   5 222]
 [  7 222   9]]
____________________
[[111   2 111]
 [  4 111   6]
 [111   8 111]]
____________________


In [18]:
a=int(input("enter your age"))
b="vote" if a>=18 else "novote"
print(b)

vote
